<script setup>
import { computed, onBeforeUnmount, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { buildDecisionContext, generateDecision } from '@/decisionEngine'
import { getDecisionRecords, saveDecisionRecord } from '@/decisionRecord'
const router=useRouter(),context=ref(buildDecisionContext()),decision=ref(generateDecision(context.value)),history=ref(getDecisionRecords()),loading=ref(false)
const risks={low:['低','success'],medium:['中','warning'],high:['高','danger'],critical:['严重','danger']},labels={production:'生产证据',equipment:'设备证据',quality:'质量证据',alarm:'报警证据'},paths={maintenance:'/maintenance',parameter_adjustment:'/production',quality_reinspection:'/quality',alarm_handling:'/alarm'}
const sourceCount=computed(()=>new Set(decision.value.evidence.filter(i=>!i.text.startsWith('已执行')).map(i=>i.type)).size)
function analyze(notify=true){loading.value=true;context.value=buildDecisionContext(context.value.batchId);decision.value=generateDecision(context.value);setTimeout(()=>{loading.value=false;if(notify)ElMessage.success('已基于当前业务事实重新分析')},220)}
function save(){const result=saveDecisionRecord(decision.value);history.value=getDecisionRecords();ElMessage[result.saved?'success':'info'](result.saved?'决策快照已保存':'该决策快照已存在')}
function go(item){router.push({path:paths[item.actionType],query:item.actionType==='parameter_adjustment'?{batchId:item.batchId,process:item.process,parameterKey:item.targetId}:item.actionType==='maintenance'?{equipmentId:item.targetId}:item.actionType==='quality_reinspection'?{batchId:item.batchId,eventId:item.targetId}:{alarmId:item.targetId}})}
const events=['production-event-changed','production-adjustment-changed','process-parameter-changed','equipment-event-changed','equipment-recovery-changed','maintenance-order-changed','quality-event-changed','quality-inspection-changed','quality-data-changed','alarm-event-changed'],refresh=()=>analyze(false);events.forEach(e=>window.addEventListener(e,refresh));onBeforeUnmount(()=>events.forEach(e=>window.removeEventListener(e,refresh)))
</script>
<template><div class="decision-live"><section class="head"><div><p>INDUSTRIAL MULTI-SOURCE DECISION</p><h2>工业智能辅助决策</h2></div><span>智能决策演示 · 基于工业仿真数据与规则推理</span></section>
<section class="panel"><header><div><i></i><h3>当前决策概览</h3></div><div><el-button type="primary" :loading="loading" @click="analyze()">重新分析</el-button><el-button @click="save">保存决策快照</el-button></div></header><div class="cards"><article><small>综合风险</small><el-tag :type="risks[decision.riskLevel][1]" effect="dark">{{risks[decision.riskLevel][0]}}风险</el-tag></article><article><small>规则置信度</small><b>{{Math.round(decision.confidence*100)}}%</b><em>工业仿真规则计算结果</em></article><article><small>关联批次</small><b>{{decision.batchId||'全局状态'}}</b></article><article><small>有效证据源</small><b>{{sourceCount}} 类</b></article></div><h3>{{decision.title}}</h3><p>{{decision.summary}}</p></section>
<section class="grid"><article class="panel"><header><div><i></i><h3>可追溯决策依据</h3></div></header><el-empty v-if="!decision.evidence.length" description="当前无业务异常证据" :image-size="55"/><div v-for="item in decision.evidence" :key="item.type+item.refId" class="evidence"><el-tag size="small">{{labels[item.type]}}</el-tag><b>{{item.refId}}</b><span>{{item.text}}</span></div></article><article class="panel"><header><div><i></i><h3>建议处置顺序</h3></div></header><el-empty v-if="!decision.recommendations.length" description="当前关联风险已解除" :image-size="55"/><div v-for="item in decision.recommendations" :key="item.actionType+item.refId" class="action"><strong>{{item.priority}}</strong><div><b>{{item.text}}</b><p>{{item.reason}}</p><small>{{item.refId}} · {{item.status}}</small></div><el-button type="primary" plain @click="go(item)">前往处理</el-button></div></article></section>
<section class="panel records"><header><div><i></i><h3>决策审计快照</h3></div></header><el-empty v-if="!history.length" description="暂无决策快照" :image-size="45"/><div v-for="item in history.slice(0,5)" :key="item.id"><b>{{item.id}}</b><span>{{item.title}}</span><span>{{Math.round(item.confidence*100)}}%</span><em>{{item.createTime}}</em></div></section></div></template>
<style scoped>
.decision-live{color:#dcecf7}.head{display:flex;align-items:center;justify-content:space-between;padding:4px 2px 15px}.head p{margin:0 0 4px;color:#3d9ccb;font:10px Consolas;letter-spacing:2px}.head h2{margin:0;font-size:21px}.head>span{color:#44b6e8;font:10px Consolas}.panel{padding:15px;background:linear-gradient(145deg,#0a2b46,#071f34);border:1px solid #204c6c}.panel>header{display:flex;align-items:center;justify-content:space-between;min-height:35px;border-bottom:1px solid #173b53}.panel header>div{display:flex;align-items:center;gap:8px}.panel header i{width:3px;height:15px;background:#2bb7ec}.panel h3{margin:0;font-size:14px}.panel>p{color:#8daabc;font-size:11px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.cards article{display:flex;gap:7px;flex-direction:column;padding:11px;background:#08243a;border:1px solid #194663}.cards small{color:#6d8da1;font-size:9px}.cards b{font:15px Consolas}.cards em{color:#4c7187;font-size:8px;font-style:normal}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0}.evidence{display:grid;grid-template-columns:85px 140px 1fr;align-items:center;gap:8px;padding:10px 2px;border-bottom:1px solid #173b53}.evidence b{color:#42b9ef;font:10px Consolas}.evidence span{color:#9ab3c2;font-size:10px}.action{display:grid;grid-template-columns:32px 1fr 82px;align-items:center;gap:9px;padding:10px 2px;border-bottom:1px solid #173b53}.action>strong{display:grid;place-items:center;width:27px;height:27px;color:#48bde9;border:1px solid #285d7a}.action b{font-size:11px}.action p{margin:4px 0;color:#7898aa;font-size:9px}.action small{color:#50768b;font-size:8px}.records>div:not(:first-child){display:grid;grid-template-columns:180px 1fr 70px 150px;gap:10px;padding:9px;border-bottom:1px solid #173b53;color:#7898aa;font-size:9px}.records b{color:#42b9ef;font:10px Consolas}.records em{font-style:normal}@media(max-width:950px){.grid{grid-template-columns:1fr}.cards{grid-template-columns:repeat(2,1fr)}}
</style>
