<script setup>
import { computed, onBeforeUnmount, ref } from 'vue'
import { ElMessage } from 'element-plus'
import BaseChart from '@/components/charts/BaseChart.vue'
import { alarmLevels, alarmRecords, alarmStatuses, alarmTrend } from '@/mock/alarm'
import { getLinkedAlarms, subscribeLinkedAlarms, updateLinkedAlarm } from '@/industrialAlarmLink'

const linkedAlarms = getLinkedAlarms()
const alarms = ref([...linkedAlarms, ...alarmRecords.filter((item) => !linkedAlarms.some((linked) => linked.id === item.id))].map(item => ({ ...item })))
const level = ref(''); const status = ref(''); const keyword = ref('')
const detailVisible = ref(false); const selected = ref(null); const assignOwner = ref('')
const filtered = computed(() => alarms.value.filter(item => (!level.value || item.level === level.value) && (!status.value || item.status === status.value) && (!keyword.value || `${item.id}${item.device}${item.reason}`.toLowerCase().includes(keyword.value.toLowerCase()))))
const stats = computed(() => ({ total: alarms.value.length, critical: alarms.value.filter(i=>i.level==='critical'&&i.status!=='closed').length, pending: alarms.value.filter(i=>i.status==='pending').length, processing: alarms.value.filter(i=>i.status==='processing').length }))
const trendOption = computed(() => ({ color:['#ef5b5b','#f1aa45','#359fe8'],tooltip:{trigger:'axis'},legend:{right:8,top:0,textStyle:{color:'#7897ad'}},grid:{left:40,right:16,top:38,bottom:24},xAxis:{type:'category',data:alarmTrend.times,axisLine:{lineStyle:{color:'#31516a'}},axisLabel:{color:'#7897ad'}},yAxis:{type:'value',minInterval:1,axisLabel:{color:'#7897ad'},splitLine:{lineStyle:{color:'rgba(100,145,177,.13)',type:'dashed'}}},series:[{name:'严重',type:'bar',stack:'alarm',data:alarmTrend.critical},{name:'警告',type:'bar',stack:'alarm',data:alarmTrend.warning},{name:'提示',type:'bar',stack:'alarm',data:alarmTrend.info}] }))
function openDetail(row){selected.value=row;assignOwner.value=row.owner==='未指派'?'':row.owner;detailVisible.value=true}
function acknowledge(){selected.value.status='processing';selected.value.owner=assignOwner.value||'当前用户';updateLinkedAlarm(selected.value);ElMessage.success('报警已确认并进入处理流程')}
function resolve(){selected.value.status='resolved';updateLinkedAlarm(selected.value);ElMessage.success('报警已标记为处理完成');detailVisible.value=false}
function closeAlarm(row){row.status='closed';updateLinkedAlarm(row);ElMessage.success(`${row.id} 已关闭`)}
const unsubscribe = subscribeLinkedAlarms((alarm) => {
  if (!alarms.value.some((item) => item.id === alarm.id)) alarms.value.unshift({ ...alarm })
})
onBeforeUnmount(unsubscribe)
</script>
<template>
 <div class="alarm-page">
  <section class="page-header"><div><p>INDUSTRIAL ALARM MANAGEMENT</p><h2>生产异常报警中心</h2></div><span class="live"><i></i>模拟数据运行</span></section>
  <section class="top-grid"><div class="stats"><article><span>报警总数</span><b>{{stats.total}}</b><el-icon><Bell/></el-icon></article><article class="red"><span>严重报警</span><b>{{stats.critical}}</b><el-icon><WarnTriangleFilled/></el-icon></article><article class="orange"><span>待处理</span><b>{{stats.pending}}</b><el-icon><Timer/></el-icon></article><article class="blue"><span>处理中</span><b>{{stats.processing}}</b><el-icon><Loading/></el-icon></article></div><article class="trend"><header><i></i><h3>今日报警趋势</h3></header><BaseChart :option="trendOption" height="170px"/></article></section>
  <section class="table-panel"><header><div><i></i><h3>报警记录</h3><span>ALARM RECORDS</span></div><div class="filters"><el-input v-model="keyword" clearable size="small" prefix-icon="Search" placeholder="编号 / 设备 / 原因"/><el-select v-model="level" clearable size="small" placeholder="报警等级"><el-option label="严重" value="critical"/><el-option label="警告" value="warning"/><el-option label="提示" value="info"/></el-select><el-select v-model="status" clearable size="small" placeholder="处理状态"><el-option v-for="(v,k) in alarmStatuses" :key="k" :label="v.label" :value="k"/></el-select></div></header>
   <el-table :data="filtered" class="alarm-table" height="410"><el-table-column prop="id" label="报警编号" min-width="165"><template #default="s"><span class="alarm-id">{{s.row.id}}</span></template></el-table-column><el-table-column prop="device" label="对象设备" min-width="145"/><el-table-column label="等级" width="80"><template #default="s"><el-tag :type="alarmLevels[s.row.level].type" effect="dark" size="small">{{alarmLevels[s.row.level].label}}</el-tag></template></el-table-column><el-table-column prop="time" label="发生时间" width="165"/><el-table-column prop="reason" label="异常原因" min-width="220" show-overflow-tooltip/><el-table-column prop="owner" label="负责人" width="90"/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="alarmStatuses[s.row.status].type" size="small">{{alarmStatuses[s.row.status].label}}</el-tag></template></el-table-column><el-table-column label="操作" width="130" fixed="right"><template #default="s"><el-button link type="primary" @click="openDetail(s.row)">详情</el-button><el-button v-if="s.row.status==='resolved'" link type="success" @click="closeAlarm(s.row)">关闭</el-button></template></el-table-column></el-table>
  </section>
  <el-dialog v-model="detailVisible" width="650px" title="报警详情与处置"><template v-if="selected"><div class="alarm-banner" :class="selected.level"><div><small>{{selected.id}}</small><h3>{{selected.reason}}</h3><p>{{selected.device}} · {{selected.time}}</p></div><el-tag :type="alarmLevels[selected.level].type" effect="dark" size="large">{{alarmLevels[selected.level].label}}报警</el-tag></div><el-descriptions :column="2" border><el-descriptions-item label="实时值">{{selected.value}}</el-descriptions-item><el-descriptions-item label="报警阈值">{{selected.threshold}}</el-descriptions-item><el-descriptions-item label="当前状态"><el-tag :type="alarmStatuses[selected.status].type">{{alarmStatuses[selected.status].label}}</el-tag></el-descriptions-item><el-descriptions-item label="处理人员">{{selected.owner}}</el-descriptions-item></el-descriptions><h4>智能处置建议</h4><el-alert :title="selected.suggestion" type="warning" :closable="false" show-icon/><h4>处置指派</h4><el-select v-model="assignOwner" placeholder="选择负责人" style="width:100%"><el-option label="李工（热工）" value="李工"/><el-option label="王工（轧制）" value="王工"/><el-option label="周工（自动化）" value="周工"/><el-option label="刘工（检测）" value="刘工"/></el-select></template><template #footer><el-button @click="detailVisible=false">取消</el-button><el-button type="warning" plain @click="acknowledge">确认并指派</el-button><el-button type="success" :disabled="selected?.status==='pending'" @click="resolve">处理完成</el-button></template></el-dialog>
 </div>
</template>
<style scoped>
.alarm-page{color:#dcecf7}.page-header{display:flex;justify-content:space-between;align-items:center;padding:4px 2px 15px}.page-header p{margin:0 0 4px;color:#3d9ccb;font:10px Consolas;letter-spacing:2px}.page-header h2{margin:0;color:#edf8ff;font-size:21px}.live{color:#6f91a8;font-size:10px}.live i{display:inline-block;width:7px;height:7px;margin-right:7px;border-radius:50%;background:#2bd398;box-shadow:0 0 8px #2bd398}.top-grid{display:grid;grid-template-columns:1.4fr 1fr;gap:12px;margin-bottom:12px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stats article{position:relative;min-height:118px;padding:20px;background:linear-gradient(145deg,#0d3453,#09263e);border:1px solid #224e6c;border-top:2px solid #31c8d8}.stats span{color:#7394aa;font-size:10px}.stats b{display:block;margin-top:10px;color:#e5f4fc;font:600 30px Consolas}.stats .el-icon{position:absolute;right:16px;bottom:18px;color:#245d7d;font-size:29px}.stats .red{border-top-color:#ef5b5b}.stats .red b{color:#ef6b6b}.stats .orange{border-top-color:#f1aa45}.stats .orange b{color:#f1aa45}.stats .blue{border-top-color:#359fe8}.stats .blue b{color:#4ab0ef}.trend,.table-panel{padding:13px 15px 4px;background:linear-gradient(145deg,#0a2b46,#071f34);border:1px solid #204c6c}.trend header,.table-panel>header>div:first-child{display:flex;align-items:center;gap:8px}.trend header i,.table-panel header i{width:3px;height:15px;background:#2bb7ec}.trend h3,.table-panel h3{margin:0;color:#dceefa;font-size:13px}.table-panel{padding-bottom:14px}.table-panel>header{height:48px;display:flex;align-items:flex-start;justify-content:space-between;border-bottom:1px solid rgba(55,107,142,.35)}.table-panel header span{color:#49748e;font:9px Consolas}.filters{display:flex;gap:8px;width:530px}.filters .el-input{flex:1}.filters .el-select{width:125px}.alarm-table{--el-table-bg-color:#0a2942;--el-table-tr-bg-color:#0a2942;--el-table-row-hover-bg-color:#123d5b;--el-table-header-bg-color:#0d3451;--el-table-border-color:#204760;--el-table-text-color:#a9c1d0;--el-table-header-text-color:#7195ad;font-size:11px}.alarm-id{color:#43b8ed;font:11px Consolas}.alarm-banner{display:flex;justify-content:space-between;align-items:center;padding:15px 18px;margin-bottom:15px;background:#f4f7f9;border-left:4px solid #389fe0}.alarm-banner.critical{border-color:#ef5b5b}.alarm-banner.warning{border-color:#e6a23c}.alarm-banner small{color:#4585a9;font:10px Consolas}.alarm-banner h3{margin:5px 0;color:#293f51;font-size:15px}.alarm-banner p{margin:0;color:#82939f;font-size:10px}.alarm-page :deep(.el-dialog h4){margin:17px 0 9px;color:#354e61;font-size:13px}@media(max-width:1150px){.top-grid{grid-template-columns:1fr}.stats article{min-height:90px}}@media(max-width:700px){.stats{grid-template-columns:repeat(2,1fr)}.table-panel>header{height:auto;flex-direction:column;gap:10px;padding-bottom:10px}.filters{width:100%}}
</style>
