<script setup>
import { computed, ref } from 'vue'
import BaseChart from '@/components/charts/BaseChart.vue'
import { graphCategories, graphLinks, graphNodes } from '@/mock/knowledgeGraph'

const categoryColors=['#36b9ed','#2ed39b','#9279ed','#f1aa45','#e66891','#ef6464']
const selectedCategory=ref('全部'); const selectedNode=ref(graphNodes[0]); const search=ref('')
const visibleNodes=computed(()=>graphNodes.filter(n=>(selectedCategory.value==='全部'||graphCategories[n.category].name===selectedCategory.value)&&(!search.value||n.name.includes(search.value))))
const visibleIds=computed(()=>new Set(visibleNodes.value.map(n=>n.id)))
const visibleLinks=computed(()=>graphLinks.filter(l=>visibleIds.value.has(l.source)&&visibleIds.value.has(l.target)))
const validNodeIds = new Set(graphNodes.map(node => node.id))
const selectedRelations = computed(() => graphLinks
  .filter(link => validNodeIds.has(link.source) && validNodeIds.has(link.target))
  .filter(link => link.source === selectedNode.value.id || link.target === selectedNode.value.id)
  .map(link => ({ ...link, relatedName: graphNodes.find(node => node.id === (link.source === selectedNode.value.id ? link.target : link.source)).name })))
const graphOption=computed(()=>({
  color:categoryColors,tooltip:{formatter:p=>p.dataType==='node'?`<b>${p.name}</b><br/>${graphCategories[p.data.category]?.name || '工业实体'}`:`${p.data?.label || '关联'}`},legend:[{data:graphCategories.map(c=>c.name),bottom:8,textStyle:{color:'#88a3b7'}}],
  series:[{type:'graph',layout:'force',roam:true,draggable:true,focusNodeAdjacency:true,data:visibleNodes.value.map(n=>({...n,itemStyle:{shadowBlur:12,shadowColor:categoryColors[n.category]+'66'}})),links:visibleLinks.value,categories:graphCategories,force:{repulsion:360,edgeLength:[80,170],gravity:.06},label:{show:true,color:'#e7f4fb',fontSize:11},edgeSymbol:['none','arrow'],edgeSymbolSize:7,lineStyle:{color:'source',opacity:.45,curveness:.08},edgeLabel:{show:true,formatter:params=>params.data?.label || '关联',color:'#64879d',fontSize:8}}]
}))
function handleClick(params){if(params.dataType==='node')selectedNode.value=graphNodes.find(n=>n.id===params.data.id)}
</script>
<template><div class="kg-page"><section class="page-header"><div><p>INDUSTRIAL ONTOLOGY KNOWLEDGE GRAPH</p><h2>工业本体知识图谱</h2></div><div class="stats"><span>本体节点 <b>{{graphNodes.length}}</b></span><span>语义关系 <b>{{graphLinks.length}}</b></span><span>本体层级 <b>{{graphCategories.length}}</b></span></div></section><nav class="layer-nav"><span>工业本体层级</span><button :class="{active:selectedCategory==='全部'}" @click="selectedCategory='全部'">全部</button><button v-for="(item,index) in graphCategories" :key="item.name" :class="{active:selectedCategory===item.name}" :style="{'--layer-color':categoryColors[index]}" @click="selectedCategory=item.name"><i></i>{{item.name}}</button></nav><section class="workspace"><article class="graph-panel"><header><div><i></i><h3>厚板生产工业知识本体</h3><span>ONTOLOGY MODEL</span></div><div><el-input v-model="search" size="small" clearable prefix-icon="Search" placeholder="搜索节点"/><el-select v-model="selectedCategory" size="small"><el-option label="全部层级" value="全部"/><el-option v-for="item in graphCategories" :key="item.name" :label="item.name" :value="item.name"/></el-select></div></header><BaseChart :option="graphOption" height="650px" @chart-click="handleClick"/><div class="tips">滚轮缩放 · 拖动画布 · 节点可拖动 · 点击查看属性</div></article><aside><header><i></i><h3>节点详情</h3></header><div class="node-profile"><span :style="{background:categoryColors[selectedNode.category]}">{{graphCategories[selectedNode.category].name}}</span><h2>{{selectedNode.name}}</h2><small>ONTOLOGY ENTITY · {{selectedNode.id}}</small></div><h4>基础信息</h4><dl class="basic-info"><div><dt>名称</dt><dd>{{selectedNode.name}}</dd></div><div><dt>类型</dt><dd>{{graphCategories[selectedNode.category].name}}</dd></div></dl><h4>实体属性</h4><dl><div v-for="(value,key) in selectedNode.properties" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></div></dl><h4>关联关系</h4><div class="relations"><div v-for="link in graphLinks.filter(l=>l.source===selectedNode.id||l.target===selectedNode.id)" :key="link.source+link.target"><span>{{link.source===selectedNode.id?'指向':'来源'}} · {{graphNodes.find(n=>n.id===(link.source===selectedNode.id?link.target:link.source))?.name}}</span><em>{{link.name}}</em></div><el-empty v-if="!graphLinks.some(l=>l.source===selectedNode.id||l.target===selectedNode.id)" description="暂无关系" :image-size="45"/></div><div class="ontology-note"><el-icon><Connection/></el-icon><p><b>工业知识本体建模</b><span>通过产品、工艺、设备、参数、质量与异常六层语义网络，为大模型提供结构化工业知识。</span></p></div></aside></section></div></template>
<style scoped>
.kg-page{color:#dcecf7}.page-header{display:flex;justify-content:space-between;align-items:center;padding:4px 2px 15px}.page-header p{margin:0 0 4px;color:#3d9ccb;font:10px Consolas;letter-spacing:2px}.page-header h2{margin:0;color:#edf8ff;font-size:21px}.stats{display:flex;gap:25px}.stats span{color:#6c8ca2;font-size:10px}.stats b{margin-left:6px;color:#40b8e9;font:16px Consolas}.workspace{display:grid;grid-template-columns:1fr 290px;gap:12px}.graph-panel,aside{position:relative;padding:15px;background:linear-gradient(145deg,#0a2b46,#071f34);border:1px solid #204c6c}.graph-panel>header{height:40px;display:flex;justify-content:space-between;border-bottom:1px solid #173e58}.graph-panel header>div{display:flex;align-items:center;gap:8px}.graph-panel header>div:last-child{width:360px}.graph-panel header .el-select{width:130px}.graph-panel header i,aside header i{width:3px;height:15px;background:#2bb7ec}.graph-panel h3,aside h3{margin:0;color:#dceefa;font-size:14px}.graph-panel header span{color:#49748e;font:9px Consolas}.tips{position:absolute;left:20px;bottom:17px;color:#496f87;font-size:9px}aside header{display:flex;align-items:center;gap:8px;padding-bottom:12px;border-bottom:1px solid #173e58}.node-profile{padding:20px 5px;border-bottom:1px solid #173e58}.node-profile>span{padding:4px 8px;color:#fff;font-size:9px}.node-profile h2{margin:12px 0 4px;color:#eef9ff}.node-profile small{color:#4b738b;font:9px Consolas}aside h4{margin:18px 0 9px;color:#7da0b5;font-size:11px}dl{margin:0}dl>div{display:flex;justify-content:space-between;padding:8px;background:#0a2942;border-bottom:1px solid #173e58;font-size:10px}dt{color:#63869d}dd{margin:0;color:#b7cfdd}.relations{max-height:170px;overflow:auto}.relations>div{display:flex;justify-content:space-between;padding:7px 9px;margin-bottom:4px;background:#0e3551;color:#9db8c8;font-size:10px}.relations em{color:#39afd9;font-style:normal}.ontology-note{display:flex;gap:10px;padding:12px;margin-top:18px;color:#3eb4df;background:rgba(38,144,191,.08);border:1px solid #245873}.ontology-note .el-icon{font-size:22px}.ontology-note p{display:flex;flex-direction:column;margin:0}.ontology-note b{font-size:10px}.ontology-note span{margin-top:4px;color:#65889e;font-size:9px;line-height:1.5}@media(max-width:900px){.workspace{grid-template-columns:1fr}.stats{display:none}}
.layer-nav{display:flex;align-items:center;gap:7px;padding:8px 12px;margin-bottom:10px;background:#092840;border:1px solid #1e4865}.layer-nav>span{margin-right:8px;color:#5d8198;font-size:9px}.layer-nav button{--layer-color:#35a9e9;display:flex;align-items:center;gap:5px;padding:5px 10px;color:#7899ae;cursor:pointer;background:transparent;border:1px solid transparent;font-size:9px}.layer-nav button i{width:6px;height:6px;border-radius:50%;background:var(--layer-color)}.layer-nav button:hover,.layer-nav button.active{color:#dceef8;background:#103b58;border-color:var(--layer-color)}.basic-info{border:1px solid #21506d}
</style>
