import { analyzeQualityStatus, appendQualityInspectionResult, getBatchQuality } from './qualityData.js'
import { linkQualityInspectionTask, startQualityEventInspection, submitQualityRecovery } from './qualityEvent.js'

const STORAGE_KEY = 'thick_plate_quality_inspection_tasks'
export const QUALITY_INSPECTION_CHANGED = 'quality-inspection-changed'
function clone(value){return value==null?value:JSON.parse(JSON.stringify(value))}
function nowText(date=new Date()){const pad=v=>String(v).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`}
function readTasks(){try{const data=JSON.parse(window.localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(data)?data:[]}catch{return[]}}
function saveTasks(tasks){window.localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks));window.dispatchEvent(new CustomEvent(QUALITY_INSPECTION_CHANGED,{detail:clone(tasks)}))}
function nextId(tasks){const now=new Date();const day=`${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}`;return `QI-${day}-${String(tasks.length+1).padStart(3,'0')}`}

export function createQualityInspectionTask(event){if(!event?.id||!['pending','inspecting'].includes(event.status))return{created:false,reason:'invalid_event',task:null};const tasks=readTasks();const duplicate=tasks.find(item=>item.eventId===event.id&&item.status!=='completed');if(duplicate)return{created:false,reason:'duplicate',task:clone(duplicate)};const data=getBatchQuality(event.batchId);const analysis=analyzeQualityStatus(data);const task={id:nextId(tasks),eventId:event.id,batchId:event.batchId,inspectionType:'质量复检',status:'pending',operator:'未指派',attempt:tasks.filter(item=>item.eventId===event.id).length+1,reason:`批次当前综合质量评分为 ${analysis?.qualityScore ?? event.qualityScoreBefore}，存在异常指标`,items:event.abnormalItems.map(item=>item.name),beforeResult:clone(data?.inspection||{}),afterResult:null,createTime:nowText(),completeTime:''};tasks.unshift(task);saveTasks(tasks);linkQualityInspectionTask(event.id,task.id);return{created:true,reason:'created',task:clone(task)}}
export function getQualityInspectionTasks(){return clone(readTasks())}
export function startQualityInspectionTask(taskId,operator){const tasks=readTasks();const task=tasks.find(i=>i.id===taskId);if(!task)return{updated:false,reason:'not_found'};if(task.status!=='pending')return{updated:false,reason:'invalid_transition',task:clone(task)};task.status='in_progress';task.operator=operator?.trim()||'质量检验员';saveTasks(tasks);startQualityEventInspection(task.eventId);return{updated:true,reason:'started',task:clone(task)}}
function deterministicInspection(before, steelGrade, attempt=1){const yieldTarget=steelGrade?.startsWith('Q550')?550:355;const tensileTarget=steelGrade?.startsWith('Q550')?670:470;const improve=(value,target)=>value>=target?value:attempt>=2?target+5:Math.round((value+target)/2);return{...clone(before),thicknessDeviation:Math.abs(before.thicknessDeviation)>.3?Math.sign(before.thicknessDeviation||1)*.18:before.thicknessDeviation,surfaceDefectRate:before.surfaceDefectRate>2?1.1:before.surfaceDefectRate,flatness:before.flatness<.85?.92:before.flatness,mechanical:{yieldStrength:improve(before.mechanical.yieldStrength,yieldTarget),tensileStrength:improve(before.mechanical.tensileStrength,tensileTarget)},defects:Object.fromEntries(Object.entries(before.defects||{}).map(([key,value])=>[key,Number(Math.min(value,key==='scale'?.4:.3).toFixed(2))]))}}
export function completeQualityInspectionTask(taskId,operator){const tasks=readTasks();const task=tasks.find(i=>i.id===taskId);if(!task)return{completed:false,reason:'not_found'};if(task.status==='completed')return{completed:true,reason:'already_completed',task:clone(task)};if(task.status!=='in_progress')return{completed:false,reason:'invalid_transition',task:clone(task)};const beforeData=getBatchQuality(task.batchId);const beforeAnalysis=analyzeQualityStatus(beforeData);const inspection=deterministicInspection(task.beforeResult,beforeData?.steelGrade,task.attempt);const result=appendQualityInspectionResult({batchId:task.batchId,taskId:task.id,inspection,time:nowText()});if(!result.appended&&result.reason!=='duplicate_task')return{completed:false,reason:result.reason,task:clone(task)};const afterData=getBatchQuality(task.batchId);const afterAnalysis=analyzeQualityStatus(afterData);task.status='completed';task.operator=operator?.trim()||task.operator;task.afterResult={inspection:clone(afterData.inspection),qualityScore:afterAnalysis.qualityScore,qualityLevel:afterAnalysis.qualityLevel.label};task.completeTime=nowText();saveTasks(tasks);const passed=['优秀','合格'].includes(afterAnalysis.qualityLevel.label);submitQualityRecovery(task.eventId,{taskId:task.id,scoreBefore:beforeAnalysis.qualityScore,scoreAfter:afterAnalysis.qualityScore,levelBefore:beforeAnalysis.qualityLevel.label,levelAfter:afterAnalysis.qualityLevel.label,verificationPassed:passed,message:passed?'复检结果达到质量仿真合格条件':'复检后仍存在质量风险，需要继续处置'});return{completed:true,reason:'completed',task:clone(task),analysis:afterAnalysis}}
